### ISSUE TITLE
https://github.com/iamwillie/covidza

### ISSUE THREAD

**Issue by NuggaN85** [iamwillie/covidza#1]
good morning,

I see html but there's everything but html how it works this script because I find it's great but it doesn't work I'd like to modify it to put it in french and change africa for France but I don't know how it works

**Comment by iamwillie** [comment]
Morning Nugga,

Although everything is rendered out as HTML, this application uses the Microsofts Blazor framework. I'm using the razor syntax on HTML. If you're interested in reading more, check out [https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)

Let me know if you have any questions.

**Comment by NuggaN85** [comment]
> Morning Nugga,
> 
> Although everything is rendered out as HTML, this application uses the Microsofts Blazor framework. I'm using the razor syntax on HTML. If you're interested in reading more, check out https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor
> 
> Let me know if you have any questions.

Yeah, okay, I don't know anything about it. Thanks anyway.

**Comment by iamwillie** [comment]
Sure thing. Be safe
